using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using FireSharp.Config;
using FireSharp.Response;
using FireSharp.Interfaces;
using LiveCharts;
using LiveCharts.Wpf;
using Guna.UI2.WinForms;
using System.Diagnostics;

namespace Unigram_Admin_App
{
    public partial class MainContainer : DevExpress.XtraEditors.XtraUserControl
    {
        private static MainContainer _instance;
        public static MainContainer Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new MainContainer();
                return _instance;
            }
        }
        public MainContainer()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the JsonDataSource asynchronously
        }

        IFirebaseConfig ifc = new FirebaseConfig()
        {
            AuthSecret = "AH6MOR5nj3YzwUvOvfHqkZ92FINoI7TZ9GS0Hphj",
            BasePath = "https://um-clone-app.firebaseio.com/"
        };

        IFirebaseClient client;

        private void timer1_Tick(object sender, EventArgs e)
        {
            label1.Text = DateTime.Now.ToLongTimeString();
            label2.Text = DateTime.Now.ToLongDateString();
        }

        private void guna2GradientButton1_Click(object sender, EventArgs e)
        {
            Scheduler scheduler = new Scheduler();
            //this.Hide();
            scheduler.Show();
            this.Show();
        }

        private void guna2GradientButton2_Click(object sender, EventArgs e)
        {
            PDF pdf = new PDF();
            //this.Hide();
            pdf.Show();
            this.Show();
        }

        private void guna2GradientButton3_Click(object sender, EventArgs e)
        {
            EditText edittext = new EditText();
            //this.Hide();
            edittext.Show();
            this.Show();
        }

        private void guna2GradientButton4_Click(object sender, EventArgs e)
        {
            SpreadSheet spreadsheet = new SpreadSheet();
            //this.Hide();
            spreadsheet.Show();
            this.Show();
        }

        private void MainContainer_Load(object sender, EventArgs e)
        {
            try
            {
                client = new FireSharp.FirebaseClient(ifc);
            }

            catch
            {
                MessageBox.Show("Không có kết nối Internet");
            }
            timer2.Start();

        }

        private void timer2_Tick(object sender, EventArgs e)
        {
            float fcpu = pCPU.NextValue();
            float fram = pRAM.NextValue(); 
            label9.Text = string.Format("{0:0.00}%", fcpu);
            label10.Text = string.Format("{0:0.00}%", fram);
        }

        private void guna2GradientPanel4_Paint(object sender, PaintEventArgs e)
        {
            
        }

        private void guna2HtmlLabel1_Click(object sender, EventArgs e)
        {
            
        }

        private void guna2HtmlLabel2_Click(object sender, EventArgs e)
        {
            
        }

        private void label13_Click(object sender, EventArgs e)
        {
            var a1 = new ProcessStartInfo("msedge.exe");
            a1.Arguments = "https://intiu.github.io/";
            Process.Start(a1);
        }

        private void guna2PictureBox4_Click(object sender, EventArgs e)
        {
            var a2 = new ProcessStartInfo("msedge.exe");
            a2.Arguments = "https://kotlinlang.org/";
            Process.Start(a2);
        }

        private void guna2PictureBox5_Click(object sender, EventArgs e)
        {
            var a3 = new ProcessStartInfo("msedge.exe");
            a3.Arguments = "https://developer.android.com/";
            Process.Start(a3);
        }

        private void guna2PictureBox10_Click(object sender, EventArgs e)
        {
            var a4 = new ProcessStartInfo("msedge.exe");
            a4.Arguments = "https://firebase.google.com/";
            Process.Start(a4);
        }

        private void guna2PictureBox9_Click(object sender, EventArgs e)
        {
            var a5 = new ProcessStartInfo("msedge.exe");
            a5.Arguments = "https://www.devexpress.com/";
            Process.Start(a5);
        }

        private void guna2PictureBox6_Click(object sender, EventArgs e)
        {
            var a6 = new ProcessStartInfo("msedge.exe");
            a6.Arguments = "https://awesomeopensource.com/project/ziyasal/FireSharp";
            Process.Start(a6);
        }

        private void guna2PictureBox7_Click(object sender, EventArgs e)
        {
            var a7 = new ProcessStartInfo("msedge.exe");
            a7.Arguments = "https://www.nuget.org/packages/MetroModernUI/";
            Process.Start(a7);
        }

        private void guna2PictureBox8_Click(object sender, EventArgs e)
        {
            var a8 = new ProcessStartInfo("msedge.exe");
            a8.Arguments = "https://gunaframework.com/";
            Process.Start(a8);
        }

        private void guna2GradientCircleButton1_Click(object sender, EventArgs e)
        {
            var a9 = new ProcessStartInfo("msedge.exe");
            a9.Arguments = "https://www.json.org/json-en.html";
            Process.Start(a9);
        }
    }
}
